name: ETL Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  extract-data-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup action
        uses: actions/setup-python@v6
        with:
            python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pandas

      - name: Show python version
        run: python --version

      - name: Run extract data
        run: python extract.py

  transform-data-job:
    runs-on: ubuntu-latest
    needs: extract-data-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run transform data
        run: python transform.py

  load-data-job:
    runs-on: ubuntu-latest
    needs: transform-data-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run load data
        run: python load.py
